"#version 330 core\n"
"\n"
"layout (location = 0) in vec3 position;\n"
"layout (location = 1) in vec3 normal;\n"
"layout (location = 2) in vec2 texCoords;\n"
"\n"
"out vec3 Normal;\n"
"out vec3 FragPos;\n"
"out vec2 TexCoords;\n"
"\n"
"uniform mat4 translation;\n"
"uniform mat4 rotation;\n"
"uniform mat4 scale;\n"
"uniform mat4 view;\n"
"uniform mat4 projection;\n"
"\n"
"void main()\n"
"{\n"
"	mat4 model = translation * rotation * scale;\n"
"	gl_Position = projection * view * model * vec4(position, 1.0f);\n"
"	TexCoords = texCoords;\n"
"	Normal = mat3(transpose(inverse(model))) * normal; //it cuts off translation and rotation and also non-uniform scaling effect\n"
"	FragPos = vec3(model * vec4(position, 1.f));\n"
"}\n"
