"#version 330 core\n"
"\n"
"in vec2 fragTexCoords;\n"
"\n"
"uniform sampler2D texSampler;\n"
"uniform vec4 color;\n"
"\n"
"out vec4 outColor;\n"
"\n"
"void main()\n"
"{\n"
"	vec4 tempColor = texture(texSampler, fragTexCoords);\n"
"	if(tempColor.a == 0)\n"
"		discard;\n"
"		\n"
"	outColor = tempColor * color;\n"
"}\n"
